import { Project, FeatureFlag, ArchitectureType } from '@sbc/core';
import type { Generator, GenerationContext } from '@sbc/core';
import type { GeneratedArtifact } from '@sbc/shared';

export class DocsGenerator implements Generator {
  readonly name = 'docs';
  readonly version = '1.0.0';
  readonly supportedFeatures: readonly FeatureFlag[] = [];
  readonly supportedArchitectures: readonly ArchitectureType[] = [];

  async generate(context: GenerationContext): Promise<GeneratedArtifact[]> {
    const { project } = context;
    const artifacts: GeneratedArtifact[] = [];

    artifacts.push({
      path: 'README.md',
      content: this.generateReadme(project),
      language: 'markdown',
    });

    artifacts.push({
      path: 'docs/ARCHITECTURE.md',
      content: this.generateArchitectureDoc(project),
      language: 'markdown',
    });

    artifacts.push({
      path: 'docs/adr/001-technology-stack.md',
      content: this.generateADR(project),
      language: 'markdown',
    });

    artifacts.push({
      path: 'docs/CONTRIBUTING.md',
      content: this.generateContributingDoc(),
      language: 'markdown',
    });

    return artifacts;
  }

  private generateReadme(project: Project): string {
    const entities = project.options.entities.map((e) => `- **${e.name}**: ${e.fields.length} fields`).join('\n');

    return `# ${project.name}

> Generated by SupportingBasesCreations

## Overview

${project.options.description || 'Enterprise-grade application generated via object-oriented configuration.'}

## Architecture

- **Type**: ${project.options.architecture}
- **Cloud**: ${project.options.infrastructure.cloud}
- **Database**: ${project.options.infrastructure.database}
- **Cache**: ${project.options.infrastructure.cache}

## Entities

${entities}

## Getting Started

\`\`\`bash
# Install dependencies
pnpm install

# Setup database
pnpm db

# Seed data
pnpm db:seed

# Run dev server
pnpm dev
\`\`\`

## Scripts

- \`pnpm dev\` - Start development server
- \`pnpm build\` - Build for production
- \`pnpm test\` - Run tests
- \`pnpm lint\` - Lint code
- \`pnpm db\` - Run database migrations

## Environment Variables

See \`.env.example\` for required variables.

## License

${project.options.license}
`;
  }

  private generateArchitectureDoc(project: Project): string {
    return `# Architecture Documentation

## System Overview

${project.name} follows a ${project.options.architecture} architecture pattern.

## Technology Stack

| Layer | Technology |
|-------|-----------|
| Frontend | Next.js 14 + React 18 |
| API | tRPC + Zod |
| Database | ${project.options.infrastructure.database} |
| ORM | Prisma |
| Cache | ${project.options.infrastructure.cache} |
| Styling | Tailwind CSS |
| Testing | Vitest + Playwright |

## Project Structure

\`\`\`
\`\`\`

## Data Model

${project.options.entities.map((e) => `### ${e.name}\n\n${e.fields.map((f) => `- \`${f.name}\`: ${f.type}${f.options.nullable ? ' (optional)' : ''}`).join('\n')}`).join('\n\n')}

## Security

- Input validation via Zod schemas
- Authentication via NextAuth.js
- Row-level security in database
- Dependency vulnerability scanning

## Deployment

See \`.github/workflows/deploy.yml\` for deployment pipeline.
`;
  }

  private generateADR(_project: Project): string {
    return `# ADR 001: Technology Stack Selection

## Status

Accepted

## Context

We needed to select a technology stack that balances developer productivity, type safety, and enterprise scalability.

## Decision

Selected the T3 Stack (TypeScript, Tailwind, tRPC) with Prisma ORM.

## Consequences

### Positive

- Full type safety from database to UI
- Rapid development with Prisma migrations
- Excellent ecosystem and community support

### Negative

- Learning curve for tRPC
- Prisma has some query limitations

## Alternatives Considered

- REST API + Express (less type safety)
- GraphQL (overkill for this scope)
- MongoDB (relational data fits PostgreSQL better)
`;
  }

  private generateContributingDoc(): string {
    return `# Contributing Guidelines

## Getting Started

1. Fork the repository
2. Create a feature branch: \`git checkout -b feature/amazing-feature\`
3. Install dependencies: \`pnpm install\`
4. Make your changes
5. Run tests: \`pnpm test\`
6. Submit a pull request

## Code Standards

- TypeScript strict mode enabled
- ESLint + Prettier for formatting
- Conventional commits required
- 80% test coverage minimum

## Commit Messages

Follow conventional commits:

- \`feat:\` New feature
- \`fix:\` Bug fix
- \`docs:\` Documentation
- \`test:\` Tests
- \`refactor:\` Code refactoring
- \`chore:\` Maintenance

## Pull Request Process

1. Update README.md if needed
2. Ensure CI passes
3. Request review from maintainers
4. Squash merge to main
`;
  }
}
