import { FeatureFlag, ArchitectureType } from '@sbc/core';
import type { Generator, GenerationContext } from '@sbc/core';
import type { GeneratedArtifact } from '@sbc/shared';

export class SecurityAuditGenerator implements Generator {
  readonly name = 'security-audit';
  readonly version = '1.0.0';
  readonly supportedFeatures: readonly FeatureFlag[] = [];
  readonly supportedArchitectures: readonly ArchitectureType[] = [];

  async generate(_context: GenerationContext): Promise<GeneratedArtifact[]> {
    const artifacts: GeneratedArtifact[] = [];

    // CI security pipeline (SAST, dependency scan, secret scan)
    artifacts.push({
      path: '.github/workflows/security.yml',
      content: this.generateSecurityCI(),
      language: 'yaml',
    });

    // Semgrep config for SAST
    artifacts.push({
      path: 'semgrep.yml',
      content: this.generateSemgrepConfig(),
      language: 'yaml',
    });

    // Snyk policy for dependency scanning
    artifacts.push({
      path: '.snyk',
      content: this.generateSnykPolicy(),
      language: 'yaml',
    });

    // Note: security-headers.ts and rateLimit.ts are generated by SecurityHardeningGenerator
    // to avoid duplication. This generator focuses on CI/CD security tooling only.

    return artifacts;
  }

  private generateSecurityCI(): string {
    return `name: Security Audit

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * 1'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci --config=auto
        env:
          SEMGREP_APP_TOKEN: \${{ secrets.SEMGREP_APP_TOKEN }}

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --debug --only-verified

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm audit --json > audit-report.json || true
      - run: pnpm sbom --json > sbom.json
      - uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            audit-report.json
            sbom.json

  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t \${{ secrets.STAGING_URL }} || true
`;
  }

  private generateSemgrepConfig(): string {
    return `rules:
  - id: no-hardcoded-secrets
    pattern-regex: (?i)(password|secret|key|token)\s*=\s*['"]\S+['"]
    languages:
      - ts
      - js
    message: "Potential hardcoded secret detected"
    severity: ERROR

  - id: no-sql-injection
    pattern-either:
      - pattern: prisma.$F.raw($X)
      - pattern: prisma.$F.queryRaw($X)
    languages:
      - ts
    message: "Raw SQL queries can lead to SQL injection"
    severity: WARNING

  - id: no-eval
    pattern: eval(...)
    languages:
      - ts
      - js
    message: "eval() is dangerous and should not be used"
    severity: ERROR
`;
  }

  private generateSnykPolicy(): string {
    return `# Snyk security policy
version: v1.25.0
ignore: {}
patch: {}
`;
  }
}
