import { Project, FeatureFlag, ArchitectureType } from "@sbc/core";
import type { Generator, GenerationContext } from "@sbc/core";
import type { GeneratedArtifact } from "@sbc/shared";

export class DockerGenerator implements Generator {
  readonly name = "docker";
  readonly version = "1.0.0";
  readonly supportedFeatures: readonly FeatureFlag[] = [];
  readonly supportedArchitectures: readonly ArchitectureType[] = [];

  async generate(context: GenerationContext): Promise<GeneratedArtifact[]> {
    const { project } = context;
    const artifacts: GeneratedArtifact[] = [];

    // vercel.json is generated by VercelDeployGenerator — do not duplicate
    // .env.example is generated by EnvGenerator — do not duplicate

    artifacts.push({
      path: "package.json",
      content: this.generatePackageJson(project),
      language: "json",
    });

    artifacts.push({
      path: "tsconfig.json",
      content: this.generateTsConfig(),
      language: "json",
    });

    artifacts.push({
      path: "next.config.ts",
      content: this.generateNextConfig(),
      language: "typescript",
    });

    artifacts.push({
      path: "postcss.config.mjs",
      content: this.generatePostcssConfig(),
      language: "javascript",
    });

    artifacts.push({
      path: "scripts/setup-db.sh",
      content: this.generateSetupDbScript(),
      language: "bash",
    });

    return artifacts;
  }

  private generateTsConfig(): string {
    return (
      JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            lib: ["ES2022", "DOM", "DOM.Iterable"],
            module: "ESNext",
            moduleResolution: "bundler",
            jsx: "preserve",
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            skipLibCheck: true,
            isolatedModules: true,
            resolveJsonModule: true,
            forceConsistentCasingInFileNames: true,
            allowJs: true,
            incremental: true,
            plugins: [{ name: "next" }],
            paths: {
              "@/*": ["./src/*"],
            },
          },
          include: [
            "next-env.d.ts",
            "**/*.ts",
            "**/*.tsx",
            ".next/types/**/*.ts",
          ],
          exclude: ["node_modules"],
        },
        null,
        2,
      ) + "\n"
    );
  }

  private generateNextConfig(): string {
    return `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  reactStrictMode: true,
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Frame-Options', value: 'DENY' },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
        ],
      },
    ];
  },
};

export default nextConfig;
`;
  }

  private generatePostcssConfig(): string {
    return `export default {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};
`;
  }

  private generateSetupDbScript(): string {
    return `#!/usr/bin/env bash
set -euo pipefail

echo "📦 Generating Prisma client..."
npx prisma generate

echo "🗄️  Pushing schema to database..."
npx prisma db push

echo "🌱 Seeding database..."
npx tsx prisma/seed.ts

echo "✅ Database setup complete!"
`;
  }

  private generatePackageJson(project: Project): string {
    const deps: Record<string, string> = {
      next: "^15.1.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      "@trpc/server": "^11.0.0",
      "@trpc/client": "^11.0.0",
      "@trpc/react-query": "^11.0.0",
      "@tanstack/react-query": "^5.62.0",
      "@prisma/client": "^6.1.0",
      "@auth/prisma-adapter": "^2.7.0",
      superjson: "^2.2.0",
      zod: "^3.24.0",
      bcryptjs: "^2.4.3",
    };

    if (project.hasFeature(FeatureFlag.AUTH)) {
      deps["next-auth"] = "^4.24.0";
    }

    const devDeps: Record<string, string> = {
      typescript: "^5.7.0",
      "@types/node": "^22.0.0",
      "@types/react": "^19.0.0",
      "@types/react-dom": "^19.0.0",
      "@types/bcryptjs": "^2.4.6",
      tailwindcss: "^4.0.0",
      "@tailwindcss/postcss": "^4.0.0",
      postcss: "^8.4.0",
      prisma: "^6.1.0",
      eslint: "^9.0.0",
      prettier: "^3.4.0",
      vitest: "^2.1.0",
      "@playwright/test": "^1.49.0",
      tsx: "^4.19.0",
    };

    const pkg = {
      name: project.name,
      version: "1.0.0",
      private: true,
      scripts: {
        dev: "next dev --turbopack",
        build: "prisma generate && next build",
        postinstall: "prisma generate",
        start: "next start",
        lint: "next lint",
        test: "vitest run",
        "test:e2e": "playwright test",
        db: "prisma migrate dev",
        "db:push": "prisma db push",
        "db:seed": "tsx prisma/seed.ts",
        "db:studio": "prisma studio",
        "setup:db": "bash scripts/setup-db.sh",
      },
      dependencies: deps,
      devDependencies: devDeps,
    };

    return JSON.stringify(pkg, null, 2) + "\n";
  }
}
