import { Project, FeatureFlag, ArchitectureType } from '@sbc/core';
import type { Generator, GenerationContext } from '@sbc/core';
import type { GeneratedArtifact } from '@sbc/shared';

export class DockerGenerator implements Generator {
  readonly name = 'docker';
  readonly version = '1.0.0';
  readonly supportedFeatures: readonly FeatureFlag[] = [];
  readonly supportedArchitectures: readonly ArchitectureType[] = [];

  async generate(context: GenerationContext): Promise<GeneratedArtifact[]> {
    const { project } = context;
    const artifacts: GeneratedArtifact[] = [];

    // vercel.json is generated by VercelDeployGenerator — do not duplicate
    artifacts.push({
      path: '.env.example',
      content: this.generateEnvExample(project),
      language: 'env',
    });

    artifacts.push({
      path: 'package.json',
      content: this.generatePackageJson(project),
      language: 'json',
    });

    return artifacts;
  }

  private generateEnvExample(project: Project): string {
    const lines: string[] = [
      `# ${project.name} Environment Variables`,
      `# Cloud-only — all services are cloud-hosted`,
      `NODE_ENV=production`,
      `DATABASE_URL=`,
      `DIRECT_URL=`,
      '',
      `# NextAuth`,
      `NEXTAUTH_URL=`,
      `NEXTAUTH_SECRET=`,
    ];

    if (project.hasFeature(FeatureFlag.AUTH_SSO)) {
      lines.push(`# SSO Provider`);
      lines.push(`SSO_CLIENT_ID=`);
      lines.push(`SSO_CLIENT_SECRET=`);
    }

    if (project.options.infrastructure.cache !== 'NONE') {
      lines.push(`# Cache (Upstash Redis)`);
      lines.push(`UPSTASH_REDIS_REST_URL=`);
      lines.push(`UPSTASH_REDIS_REST_TOKEN=`);
    }

    return lines.join('\n') + '\n';
  }

  private generatePackageJson(project: Project): string {
    const deps: Record<string, string> = {
      next: '^14.0.0',
      react: '^18.2.0',
      'react-dom': '^18.2.0',
      '@trpc/server': '^10.45.0',
      '@trpc/client': '^10.45.0',
      '@trpc/react-query': '^10.45.0',
      '@tanstack/react-query': '^5.0.0',
      '@prisma/client': '^5.0.0',
      superjson: '^2.0.0',
      zod: '^3.22.0',
    };

    if (project.hasFeature(FeatureFlag.AUTH)) {
      deps['next-auth'] = '^4.24.0';
    }

    const devDeps: Record<string, string> = {
      typescript: '^5.4.0',
      '@types/node': '^20.0.0',
      '@types/react': '^18.2.0',
      '@types/react-dom': '^18.2.0',
      tailwindcss: '^3.4.0',
      postcss: '^8.4.0',
      autoprefixer: '^10.4.0',
      prisma: '^5.0.0',
      eslint: '^8.0.0',
      prettier: '^3.2.0',
    };

    const pkg = {
      name: project.name,
      version: '1.0.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint',
        db: 'prisma migrate dev',
        'db:seed': 'tsx prisma/seed.ts',
      },
      dependencies: deps,
      devDependencies: devDeps,
    };

    return JSON.stringify(pkg, null, 2) + '\n';
  }
}
