import { Project, FeatureFlag, ArchitectureType } from "@sbc/core";
import type { Generator, GenerationContext } from "@sbc/core";
import type { GeneratedArtifact } from "@sbc/shared";

export class DockerGenerator implements Generator {
  readonly name = "docker";
  readonly version = "1.0.0";
  readonly supportedFeatures: readonly FeatureFlag[] = [];
  readonly supportedArchitectures: readonly ArchitectureType[] = [];

  async generate(context: GenerationContext): Promise<GeneratedArtifact[]> {
    const { project } = context;
    const artifacts: GeneratedArtifact[] = [];

    // vercel.json is generated by VercelDeployGenerator — do not duplicate
    artifacts.push({
      path: ".env.example",
      content: this.generateEnvExample(project),
      language: "env",
    });

    artifacts.push({
      path: "package.json",
      content: this.generatePackageJson(project),
      language: "json",
    });

    return artifacts;
  }

  private generateEnvExample(project: Project): string {
    const lines: string[] = [
      `# ${project.name} Environment Variables`,
      `# Cloud-only — all services are cloud-hosted`,
      `NODE_ENV=production`,
      `DATABASE_URL=`,
      `DIRECT_URL=`,
      "",
      `# NextAuth`,
      `NEXTAUTH_URL=`,
      `NEXTAUTH_SECRET=`,
    ];

    if (project.hasFeature(FeatureFlag.AUTH_SSO)) {
      lines.push(`# SSO Provider`);
      lines.push(`SSO_CLIENT_ID=`);
      lines.push(`SSO_CLIENT_SECRET=`);
    }

    if (project.options.infrastructure.cache !== "NONE") {
      lines.push(`# Cache (Upstash Redis)`);
      lines.push(`UPSTASH_REDIS_REST_URL=`);
      lines.push(`UPSTASH_REDIS_REST_TOKEN=`);
    }

    return lines.join("\n") + "\n";
  }

  private generatePackageJson(project: Project): string {
    const deps: Record<string, string> = {
      next: "^15.1.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      "@trpc/server": "^11.0.0",
      "@trpc/client": "^11.0.0",
      "@trpc/react-query": "^11.0.0",
      "@tanstack/react-query": "^5.62.0",
      "@prisma/client": "^6.1.0",
      "@auth/prisma-adapter": "^2.7.0",
      superjson: "^2.2.0",
      zod: "^3.24.0",
      bcryptjs: "^2.4.3",
    };

    if (project.hasFeature(FeatureFlag.AUTH)) {
      deps["next-auth"] = "^5.0.0-beta.25";
    }

    const devDeps: Record<string, string> = {
      typescript: "^5.7.0",
      "@types/node": "^22.0.0",
      "@types/react": "^19.0.0",
      "@types/react-dom": "^19.0.0",
      "@types/bcryptjs": "^2.4.6",
      tailwindcss: "^4.0.0",
      "@tailwindcss/postcss": "^4.0.0",
      postcss: "^8.4.0",
      prisma: "^6.1.0",
      eslint: "^9.0.0",
      prettier: "^3.4.0",
      vitest: "^2.1.0",
      "@playwright/test": "^1.49.0",
      tsx: "^4.19.0",
    };

    const pkg = {
      name: project.name,
      version: "1.0.0",
      private: true,
      scripts: {
        dev: "next dev --turbopack",
        build: "next build",
        start: "next start",
        lint: "next lint",
        test: "vitest run",
        "test:e2e": "playwright test",
        db: "prisma migrate dev",
        "db:push": "prisma db push",
        "db:seed": "tsx prisma/seed.ts",
        "db:studio": "prisma studio",
      },
      dependencies: deps,
      devDependencies: devDeps,
    };

    return JSON.stringify(pkg, null, 2) + "\n";
  }
}
