import { Project, FeatureFlag, ArchitectureType } from '@sbc/core';
import type { Generator, GenerationContext } from '@sbc/core';
import type { GeneratedArtifact } from '@sbc/shared';

export class ObservabilityStackGenerator implements Generator {
  readonly name = 'observability';
  readonly version = '1.0.0';
  readonly supportedFeatures: readonly FeatureFlag[] = [];
  readonly supportedArchitectures: readonly ArchitectureType[] = [];

  async generate(context: GenerationContext): Promise<GeneratedArtifact[]> {
    const { project } = context;
    const artifacts: GeneratedArtifact[] = [];

    artifacts.push({
      path: 'src/lib/observability/tracing.ts',
      content: this.generateTracing(project),
      language: 'typescript',
    });

    artifacts.push({
      path: 'src/lib/observability/logger.ts',
      content: this.generateLogger(project),
      language: 'typescript',
    });

    artifacts.push({
      path: 'src/lib/observability/metrics.ts',
      content: this.generateMetrics(project),
      language: 'typescript',
    });

    artifacts.push({
      path: 'src/app/api/health/route.ts',
      content: this.generateHealthRoute(),
      language: 'typescript',
    });

    // vercel.json is generated by VercelDeployGenerator — observability config
    // (analytics, speedInsights) is documented in docs/SETUP.md instead

    return artifacts;
  }

  private generateTracing(_project: Project): string {
    return `import { NodeSDK } from '@opentelemetry/sdk-node';
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import { Resource } from '@opentelemetry/resources';
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions';
import { SimpleSpanProcessor } from '@opentelemetry/sdk-trace-base';

const resource = new Resource({
  [SemanticResourceAttributes.SERVICE_NAME]: process.env.OTEL_SERVICE_NAME || 'sbc-app',
  [SemanticResourceAttributes.SERVICE_VERSION]: process.env.npm_package_version || '1.0.0',
  [SemanticResourceAttributes.DEPLOYMENT_ENVIRONMENT]: process.env.NODE_ENV || 'development',
});

const exporter = new OTLPTraceExporter({
  url: process.env.OTEL_EXPORTER_OTLP_ENDPOINT || 'https://api.honeycomb.io/v1/traces',
  headers: process.env.HONEYCOMB_API_KEY ? { 'x-honeycomb-team': process.env.HONEYCOMB_API_KEY } : {},
});

const sdk = new NodeSDK({
  resource,
  spanProcessor: new SimpleSpanProcessor(exporter),
});

export function initTracing(): void {
  sdk.start();
  process.on('SIGTERM', () => sdk.shutdown().catch(console.error));
}

export { sdk };
`;
  }

  private generateLogger(_project: Project): string {
    return `export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'fatal';

interface LogEntry {
  level: LogLevel;
  message: string;
  service: string;
  environment: string;
  timestamp: string;
  [key: string]: unknown;
}

const service = process.env.OTEL_SERVICE_NAME || 'sbc-app';
const environment = process.env.NODE_ENV || 'development';

let sentryInitialized = false;

async function initSentry(): Promise<void> {
  if (sentryInitialized || !process.env.SENTRY_DSN) return;
  try {
    const Sentry = await import('@sentry/node');
    Sentry.init({
      dsn: process.env.SENTRY_DSN,
      environment,
      tracesSampleRate: 1.0,
    });
    sentryInitialized = true;
  } catch {
    // @sentry/node not installed — skip
  }
}

initSentry();

export const logger = {
  debug(message: string, meta?: Record<string, unknown>): void {
    console.debug(JSON.stringify({ level: 'debug', message, service, environment, timestamp: new Date().toISOString(), ...meta }));
  },
  info(message: string, meta?: Record<string, unknown>): void {
    console.log(JSON.stringify({ level: 'info', message, service, environment, timestamp: new Date().toISOString(), ...meta }));
  },
  warn(message: string, meta?: Record<string, unknown>): void {
    console.warn(JSON.stringify({ level: 'warn', message, service, environment, timestamp: new Date().toISOString(), ...meta }));
  },
  error(message: string, meta?: Record<string, unknown>): void {
    console.error(JSON.stringify({ level: 'error', message, service, environment, timestamp: new Date().toISOString(), ...meta }));
    if (process.env.SENTRY_DSN) {
      import('@sentry/node').then(Sentry => Sentry.captureException(new Error(message))).catch(() => {});
    }
  },
  fatal(message: string, meta?: Record<string, unknown>): void {
    console.error(JSON.stringify({ level: 'fatal', message, service, environment, timestamp: new Date().toISOString(), ...meta }));
    if (process.env.SENTRY_DSN) {
      import('@sentry/node').then(Sentry => Sentry.captureException(new Error(message))).catch(() => {});
    }
  },
};

export function logRequest(req: Request, res: Response, duration: number): void {
  logger.info('http_request', {
    method: req.method,
    url: req.url,
    statusCode: res.status,
    durationMs: duration,
    userAgent: req.headers.get('user-agent'),
    ip: req.headers.get('x-forwarded-for') || 'unknown',
  });
}
`;
  }

  private generateMetrics(_project: Project): string {
    return `import { MeterProvider, PeriodicExportingMetricReader } from '@opentelemetry/sdk-metrics';
import { OTLPMetricExporter } from '@opentelemetry/exporter-metrics-otlp-http';
import { Resource } from '@opentelemetry/resources';
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions';
import { metrics } from '@opentelemetry/api';

const resource = new Resource({
  [SemanticResourceAttributes.SERVICE_NAME]: process.env.OTEL_SERVICE_NAME || 'sbc-app',
});

const metricReader = new PeriodicExportingMetricReader({
  exporter: new OTLPMetricExporter({
    url: process.env.OTEL_EXPORTER_OTLP_METRICS_ENDPOINT || 'https://api.honeycomb.io/v1/metrics',
  }),
  exportIntervalMillis: 10000,
});

const meterProvider = new MeterProvider({ resource, readers: [metricReader] });
metrics.setGlobalMeterProvider(meterProvider);

export const meter = metrics.getMeter('sbc-app-meter');

export const httpRequestCounter = meter.createCounter('http_requests_total', {
  description: 'Total number of HTTP requests',
});

export const httpRequestDuration = meter.createHistogram('http_request_duration_seconds', {
  description: 'HTTP request duration in seconds',
});

export const activeConnections = meter.createUpDownCounter('active_connections', {
  description: 'Number of active connections',
});
`;
  }

  private generateHealthRoute(): string {
    return `import { NextResponse } from 'next/server';

export async function GET() {
  const checks = {
    database: await checkDatabase(),
    cache: await checkCache(),
    memory: process.memoryUsage(),
    uptime: process.uptime(),
    timestamp: new Date().toISOString(),
  };

  const healthy = checks.database && checks.cache;

  return NextResponse.json(
    { status: healthy ? 'healthy' : 'degraded', checks },
    { status: healthy ? 200 : 503 }
  );
}

async function checkDatabase(): Promise<boolean> {
  const dbUrl = process.env.DATABASE_URL ?? process.env.SUPABASE_URL;
  if (!dbUrl) return false;
  try {
    const res = await fetch(\`\${dbUrl}/rest/v1/?apikey=\${process.env.SUPABASE_ANON_KEY ?? ''}\`, {
      signal: AbortSignal.timeout(3000),
    });
    return res.ok || res.status === 401; // 401 means DB is up, just no auth
  } catch {
    return false;
  }
}

async function checkCache(): Promise<boolean> {
  const redisUrl = process.env.UPSTASH_REDIS_REST_URL;
  const redisToken = process.env.UPSTASH_REDIS_REST_TOKEN;
  if (!redisUrl || !redisToken) return true; // Cache is optional — pass if not configured
  try {
    const res = await fetch(\`\${redisUrl}/ping\`, {
      headers: { Authorization: \`Bearer \${redisToken}\` },
      signal: AbortSignal.timeout(3000),
    });
    return res.ok;
  } catch {
    return false;
  }
}
`;
  }
}
